### ISSUE TITLE
GAP catches interrupt

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/LibGAP.jl#2]
When one loads libgap into julia then a double ''\<ctr>-C'' entered in a long julia computation
is apparently caught by GAP,
with the effect that julia is left, with the well-known message that is printed by GAP:
"gap: you hit '\<ctr>-C' twice in a second, goodbye."

Is this intended?

**Comment by fingolfin** [comment]
Migrated to https://github.com/oscar-system/GAPJulia/issues/74
